[package]
name = "wifi_tracking_api"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3.2"
parking_lot = "0.11.2"
tokio = { version = "1.15.0", features = ["full"] }
serde = { version = "1.0.135", features = ["derive"] }
serde_json = { version = "1.0.78" }
itertools = "0.10.2"
